# Uncomment this line to define a global platform for your project
  platform :ios, '9.0'

target 'BitcoinBurgers' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BitcoinBurgers
  pod 'RealmSwift'
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON'

  target 'BitcoinBurgersTests' do
    inherit! :search_paths
    pod 'RealmSwift'
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON'
  end

  target 'BitcoinBurgersUITests' do
    inherit! :search_paths
    pod 'RealmSwift'
    pod 'SwiftyJSON'
  end

end
